### PR TITLE
add bottom bar for manager app

### PR DESCRIPTION
**Pull request by f1010**
Refactored code structure and added ui for bottom bar in manager app

### CODE REVIEW

**Comment by arthurgustin** [comment]
Hi @f1010 ,
I can"t run it on my phone, I got this message:
```
Installing build\app\outputs\apk\app.apk...
I/FlutterActivityDelegate(13616): onResume setting current activity to this
E/flutter (13616): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (13616): NoSuchMethodError: Attempted to use type 'HomeScreen' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the HomeScreen constructor and forget the 'new' operator?
E/flutter (13616): Receiver: HomeScreen
E/flutter (13616): Tried calling: HomeScreen()
E/flutter (13616): #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
E/flutter (13616): #1      main (file:///C:/Users/arthur/dart/OM-App/lib/main.dart:14)
E/flutter (13616): #2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:279)
E/flutter (13616): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
Syncing files to device Redmi Note 3...
```

Which version do you use ? (EDIT: just saw the pubspec, I will update my version) The code is all red on my intellij, and `new` keywords are missing for constructors.

Also, your commit message must be in the present tense (`add` instead of `added`)

**Review by arthurgustin — CHANGES_REQUESTED** [review]
Commit message must be in present tense.
Also, I don't understand the naming for `StepsContainer`, can you elaborate please ?

**Comment by arthurgustin** [comment]
Ok I successfuly launched it on my phone. that's good, thought the registration workflow has disapeared !
Please remove `(ui)` in your commit message because you also did a code refactor and your impact is not localized to UI only !

**Comment by f1010** [comment]
Do you prefer to use Redux for the rest of the app?

**Comment by f1010** [comment]
The reason for name `StepsContainer` is that it will act as a container widget for the whole form.

**Review by f1010 — COMMENTED** [review]
What needs to be changed exactly?

**Comment by arthurgustin** [comment]
@f1010 I dont care if it's redux or not. I think that for most workflow, staful widget will be enough. You didn't change the commit message, you just changed  the PR title, in order to change the commit message you need to do a `git commit --amend` if it's your last commit, otherwise you can do a `git rebase -i master` to rewrite history of your branch.

Example of commit message I expect: `feat: add navigation menu`
And in the description message you can say that you also refactored the code

**Comment by f1010** [comment]
Can you please review the commits now?

**Review by arthurgustin — APPROVED** [review]

**Pull request merged**
